# Setup
title:               HCI projects
tagline:             ''
description:         'HCI projects'
url:                 https://rukalchau.github.io
baseurl:             '/HCI'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
