# Setup
title:               HCI projects diary
tagline:             ''
description:         'HCI projects diary'
url:                 https://rukalchau.github.io
baseurl:             '/HCI'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Luffy
  url:               
  email:             rukalchau@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
